# netlify.toml

[build]
  command = "ng build" # Your build command
  #publish = "dist/your-app-name" # The folder Netlify should publish

[build.environment]
  NPM_FLAGS = "--force" # Pass the --force flag to npm install

# Add any other build settings, environment variables, redirects, headers, etc., as needed.
